var username ;
var myName="Muhammad Yaqoob";
var message="Hello World";
alert(message);
var age=17;
alert(age);
var track="Certified Mobile Application Development";
alert(track);
alert("Pizza\nPizz\nPiz\nPi\nP");
var email="muhammadyaqoob46@gmail.com";
alert("My email address is "+email);
var book="A smarter way to learn JavaScript";
alert("I am trying to learn from the book "+book);
document.write("Yah! I can write HTML content through JavaScript");
var design="▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬";
alert(design);